### ISSUE TITLE
please add a "getPid :: ProcessHandle -> IO (Maybe Int)"

### ISSUE THREAD

**Issue by sternmull** [haskell/process#108]
At the moment there is no way to get the PID of the subprocess. This can be very useful for logging or to use external commands to interact with a process.

This would be the equivalent of https://docs.python.org/3/library/subprocess.html#subprocess.Popen.pid

**Comment by snoyberg** [comment]
I'm not opposed to such an addition, though the caveats that go along with it—specifically that the process may have died since the PID was acquired—need to be spelled out in the docs.

I'm not familiar enough with the Windows side of things to know if this has a natural implementation there, do you have any insight?

Finally, are you interested in writing a PR for this?

**Comment by EpicOrange** [comment]
Seems like this can be closed!

**Comment by snoyberg** [comment]
Thanks for pinging! Closing
