### ISSUE TITLE
Confusing documentation for createProcess_

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/process#192]
I'm really confused by the documentation for `createProcess_`.  For reference, the documentation for `createProcess` (without underbar) says

```
createProcess
    :: CreateProcess
    -> IO (Maybe Handle, Maybe Handle, Maybe Handle, ProcessHandle) 
```

"... createProcess returns (mb_stdin_hdl, mb_stdout_hdl, mb_stderr_hdl, ph)"

and the documentation for `createProcess_` (with underbar) says

```
createProcess_
    :: String
    -> CreateProcess
    -> IO (Maybe Handle, Maybe Handle, Maybe Handle, ProcessHandle)
```

"This function is almost identical to `createProcess`. The only differences are:

*    Handles provided via UseHandle are not closed automatically.
*    This function takes an extra String argument to be used in creating error messages.
*    use_process_jobs can be set in CreateProcess since 1.5.0.0 in order to create an I/O completion port to monitor a process tree's progress on Windows.

The function also returns two new handles: * an I/O Completion Port handle on which events will be signaled. * a Job handle which can be used to kill all running processes."

But where are these two new handles?  Are they two of the three returned in the tuple from the function?  If so then those three are not stdin, stdout, and stderr like they are for `createProcess`, so `createProcess_` is *not* "almost identical to `createProcess`". If they are not part of that tuple then where are they? Something needs to be clarified here.

**Comment by snoyberg** [comment]
This looks to me like an accidental merging of two functions' docs, see:

https://github.com/haskell/process/commit/3a5935ce6353e5c9e35214a070c31342098e5c6c#diff-c5db4cc90b03efcbad68033c8d800d7bL73

@Mistuke would you mind having a look and seeing if that's an accurate description?

**Comment by Mistuke** [comment]
Hmm it looks like I wrote the docs without taking into account the surrounding context.  The doc is accurate, but the last two points aren't a difference with `createProcess` as the same behavior can be gotten with `createProcess` by setting `use_process_jobs`.

> * use_process_jobs can be set in CreateProcess since 1.5.0.0 in order to create an I/O completion port to monitor a process tree's progress on Windows. 

This and the part below it should also be under the docs for `createProcess`.

> But where are these two new handles? Are they two of the three returned in the tuple from the function?

They are in `ProcessHandle`. when `use_process_jobs` is used you get a `OpenExtHandle` back instead of `OpenHandle`. The former gives you two handles instead of one.

They are returned like this because most functions in `process` need either one or both handles depending on whether `use_process_jobs` is used. For instance `terminateProcess` with `use_process_jobs` requires both handles, otherwise it can't work which is why we keep them together like this.

**Comment by tomjaguarpaw** [comment]
Thanks @snoyberg and @Mistuke. I attempted to fix the Haddock at https://github.com/haskell/process/pull/193.
