### ISSUE TITLE
Consider using MonadIO instead of IO

### ISSUE THREAD

**Issue by expipiplus1** [haskell/process#48]
Using `MonadIO` would allow people to avoid wrapping every call to a function in this package with `liftIO` when working in a `MonadIO` instance.

**Comment by snoyberg** [comment]
This is unlikely to happen for three reasons:

1. It's a (slightly) breaking change, in that it can mess with type inference
2. It adds a new dependency
3. Most of the low-level packages like process have stuck to monomorphic APIs based around `IO` instead of generalizing, and I don't believe we should break that consistency haphazardly

**Comment by hvr** [comment]
@snoyberg just for the record, in a couple of years you could cross off "2." due to https://ghc.haskell.org/ticket/10773 :-)

**Comment by simonmar** [comment]
Let me add a couple more reasons not to do this:

4. It adds no new functionality, while making the types more complex
5. The IO type is more precise than `MonadIO`.

In general it makes no sense to generalise return types like this.
