### ISSUE TITLE
Primitives do not compose well

### ISSUE THREAD

**Issue by sol** [haskell/process#5]
Working with process always felt clumsy to me.  While sometimes, there are simple primitives that fit my purpose, oftentimes I end up using `createProcess` and dealing with all the complexity myself.

A recent example is that I started out with `readProcess` but at the point where I wanted to use arbitrary shell commands I again had to switch to `createProcess`.

One thing that I think would increase composability would be to work with `CmdSpec` instead of either `String` or `(FilePath, [String])` in most places.  Again, taking `readProcess` as an example, that would mean to change the type to

```haskell
readProcess :: CmdSpec -> String -> IO String
```

which then can be used to run either raw commands

```haskell
readProcess (RawCommand "echo" ["foo"]) ""
```
or shell commands

```haskell
readProcess (ShellCommand "echo foo") ""
```

In addition, we could also allow to use string literals as shell commands by adding an `IsString` instance for `CmdSpec`:

```haskell
readProcess "echo foo" ""
```

(If you want to get fancy + are not afraid of partial functions, you can do something similar for raw commands and `OverloadedLists`.)

**Comment by dcoutts** [comment]
`readProcess` is not supposed to be a primitive. `createProcess` is the primitive and `readProcess` etc are just common convenience versions. If we make those more general then it makes them less convenient for the common cases they do match well.

**Comment by dcoutts** [comment]
What's missing given the current naming conventions is `readCommand` and `readCommandWithExitCode`

**Comment by snoyberg** [comment]
I think what users may want is a version of `readProcess` and `readProcessWithExitCode` that acts on a `CreateProcess` value, with the caveat that it overwrites the std_in, std_out and std_err fields. @sol Does that sound like it would help?

We can probably add this under a different name without breaking the API.

**Comment by sheyll** [comment]
Well just a follow-up: 
For me it was easier to use a conduit based library which wraps around createProcess. The implementation of something similar to readProcess _is_ non-trivial and also not something I would like to do at work.
I do not think that readProcess is very useful. For me it was simply misleading because I hit an unexpected wall and spent hours finding out, that basically I could not do what I wanted.
I still do not understand dcoutts point on readProcess not bein a primitve though. I mean just be changing the API a tiny little bit it could be orders of magnitudes more composable.

**Comment by snoyberg** [comment]
I believe pull request #24 (plus d0a62be4d7d5867676da285540c21e2e2d8cd0c7) addresses this issue. Closing, if there is still missing functionality, please reopen.

**Comment by tomjaguarpaw** [comment]
Partly addressed by https://github.com/haskell/process/pull/358, but I think we can do more.
