### ISSUE TITLE
There's no readCreateProcessWithExitCodeWithoutStdErr

### ISSUE THREAD

**Issue by expipiplus1** [haskell/process#89]
It would be handy to have a function which looks like this `CreateProcess ->
String -> IO (ExitCode,String)`. It behaves the same as `readCreateProcess`
except that `stderr` is inherited.

It shouldn't usually be a problem implementing this functionality outside of
`process` except that in this case it requires either catching and parsing the
`IOError` thrown from `readCreateProcess` or reimplementing most of
`readCreateProcessWithExitCode` and a handful of utility functions in
`System.Process`.

An alternative to writing this function would be to expose the building blocks
necessary from System.Process.

I'm sure there's a better name to be had too!

**Comment by snoyberg** [comment]
I'm very hesitant about adding something like this, for two reasons:

* There are three standard handles, and providing a different function for each combination of inherited/not inherited for each of them leads to 8 functions
* I really don't want to be encouraging usage of these functions, since they are using `String`. Instead, reading in binary data over the raw `Handle` is superior

We already discussed including `bytestring`-based functions in this package, and ultimately decided not to (see #36). I'm still not sure I made the right decision on that.

In any event, providing the means to more directly get the desired behavior here, at the very least via improved docs, seems like a good thing. If I was to write this, I would not rely on the lazy I/O approach used inside this package, but instead use the `async` package. (And I'm hesitant to mention it, but I'd probably also use my typed-process package, which wraps up the process API in something I consider superior.)

Anyway, here's how I'd achieve what you're looking for with typed-process:

```haskell
#!/usr/bin/env stack
{- stack --resolver lts-7.14 --install-ghc runghc
    --package async --package typed-process
-}
{-# LANGUAGE OverloadedStrings #-}
import System.Process.Typed
import qualified Data.ByteString.Lazy.Char8 as BL
import Control.Concurrent.STM (atomically)

main :: IO ()
main = do
    let pc = setStdout byteStringOutput
           $ setStdin (byteStringInput "This is the list of words:\n\n")
           $ proc "cat" ["-", "/usr/share/dict/words"]
    lbs <- withProcess_ pc $ atomically . getStdout

    BL.putStr $ BL.take 1000 lbs
```

**Comment by expipiplus1** [comment]
I'd not seen `typed-process`, looks very useful. Thanks.

> There are three standard handles, and providing a different function for each combination of inherited/not inherited for each of them leads to 8 function

I agree.

Were this request to go ahead I'd probably have asked for something similar for bytestrings in process-extras :)

That example seems much nicer than what's going on inside `process`. I'd be happy with some improved documentation now.

Thanks!

**Comment by snoyberg** [comment]
There's a tutorial on typed-process at https://haskell-lang.org/library/typed-process. If you have specific ideas for improvement, suggestions and PRs are definitely welcome. I've been debating for a while proposing some radical changes (or at least additions) to process based on what I've done in typed-process, but haven't followed through on them.

**Comment by expipiplus1** [comment]
A link to typed-process somewhere would be a very useful addition to this package's documentation.

**Comment by snoyberg** [comment]
I don't know how appropriate that would be, I think some people may take
exception with such a move. In any event, I won't be the person to either
suggest or approve the change, so if you'd like to see it happen, can I
suggest you open a PR and I'll ask someone else to review?

**Comment by expipiplus1** [comment]
Understood, thanks.
